volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO = "mongodb+srv://Ishaan:ishaan@crmcluster.yemfrh4.mongodb.net/apilux?retryWrites=true&w=majority&appName=CRMCluster"
      - ENVIRONMENT = "production"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
