version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trafix-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: unless-stopped
